version: '3.9'
services:
  db:
    image: postgres:16.4
    container_name: nimble-gateway-payment-db
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: nimble_gateway_payment
      POSTGRES_TCP_PORT: 5432
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nimble-gateway-payment-network
  nimble-gateway-payment:
    image: edielsonassis/nimble-gateway-payment
    container_name: nimble-gateway-payment-api
    restart: always
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/nimble_gateway_payment?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: admin123
      SPRING.FLYWAY.URL: jdbc:postgresql://db:5432/nimble_gateway_payment?useTimezone=true&serverTimezone=UTC
      SPRING.FLYWAY.USER: postgres
      SPRING.FLYWAY.PASSWORD: admin123
    ports:
      - 8080:8080
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - nimble-gateway-payment-network
networks:
  nimble-gateway-payment-network:
    driver: bridge
volumes:
  postgres-data: