# Server settings
server:
  port: ${SERVER_PORT:8080}
  error:
    include-stacktrace: never

# Spring settings
      
# Spring ansi settings
spring:
  output:
    ansi:
      enabled: always

# Spring datasource settings
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:nimble_gateway_payment}?useTimezone=true&serverTimezone=UTC
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234567}
  
# Spring JPA settings  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

# Spring flyway settings
  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:nimble_gateway_payment}?useTimezone=true&serverTimezone=UTC
    schemas: ${DB_NAME:nimble_gateway_payment}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234567}